import {
  SiAstro,
  SiAxios,
  SiBootstrap,
  SiBun,
  SiCss,
  SiDocker,
  SiExpo,
  SiExpress,
  SiFirebase,
  SiFramer,
  SiGin,
  SiGithub,
  SiGo,
  SiHtml5,
  SiJavascript,
  SiJetpackcompose,
  SiKotlin,
  SiLaravel,
  SiMdx,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiReact,
  SiRedux,
  SiShadcnui,
  SiSqlite,
  SiSupabase,
  SiSwagger,
  SiTailwindcss,
  SiTanstack,
  SiTypescript,
  SiVite,
  SiVuedotjs,
  SiYarn,
  SiZod,
  SiJira,
} from "react-icons/si"
import { FaSlack } from "react-icons/fa"
import type { IconType } from "react-icons"
import { Box, type LucideIcon } from "lucide-react"

type StackIconComponent = IconType | LucideIcon

const stackIcons: Record<string, StackIconComponent> = {
  html: SiHtml5,
  html5: SiHtml5,
  css: SiCss,
  css3: SiCss,
  bootstrap: SiBootstrap,
  tailwindcss: SiTailwindcss,
  tailwind: SiTailwindcss,
  "tailwind css": SiTailwindcss,
  javascript: SiJavascript,
  js: SiJavascript,
  typescript: SiTypescript,
  ts: SiTypescript,
  react: SiReact,
  "react.js": SiReact,
  "react native": SiReact,
  vite: SiVite,
  vue: SiVuedotjs,
  "vue.js": SiVuedotjs,
  vuejs: SiVuedotjs,
  jira: SiJira,
  slack: FaSlack,
  astro: SiAstro,
  "astro.js": SiAstro,
  "shadcn ui": SiShadcnui,
  shadcnui: SiShadcnui,
  tanstack: SiTanstack,
  axios: SiAxios,
  zod: SiZod,
  "framer motion": SiFramer,
  framer: SiFramer,
  redux: SiRedux,
  "next.js": SiNextdotjs,
  nextjs: SiNextdotjs,
  prisma: SiPrisma,
  "node.js": SiNodedotjs,
  nodejs: SiNodedotjs,
  "express.js": SiExpress,
  expressjs: SiExpress,
  express: SiExpress,
  go: SiGo,
  golang: SiGo,
  gin: SiGin,
  "gin gonic": SiGin,
  swagger: SiSwagger,
  php: SiPhp,
  laravel: SiLaravel,
  kotlin: SiKotlin,
  "jetpack compose": SiJetpackcompose,
  jetpackcompose: SiJetpackcompose,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  "postgre sql": SiPostgresql,
  mysql: SiMysql,
  "my sql": SiMysql,
  firebase: SiFirebase,
  supabase: SiSupabase,
  docker: SiDocker,
  npm: SiNpm,
  yarn: SiYarn,
  bun: SiBun,
  github: SiGithub,
  expo: SiExpo,
  mdx: SiMdx,
  sqlite: SiSqlite,
}

const stackColors: Record<string, string> = {
  html: "#E34F26",
  html5: "#E34F26",
  css: "#1572B6",
  css3: "#1572B6",
  bootstrap: "#7952B3",
  tailwindcss: "#06B6D4",
  tailwind: "#06B6D4",
  "tailwind css": "#06B6D4",
  javascript: "#F7DF1E",
  js: "#F7DF1E",
  typescript: "#3178C6",
  ts: "#3178C6",
  react: "#61DAFB",
  "react.js": "#61DAFB",
  "react native": "#61DAFB",
  vite: "#646CFF",
  vue: "#4FC08D",
  "vue.js": "#4FC08D",
  vuejs: "#4FC08D",
  jira: "#0052CC",
  slack: "#4A154B",
  astro: "#BC52EE",
  "astro.js": "#BC52EE",
  tanstack: "#FF4154",
  axios: "#5A29E4",
  zod: "#3E67B1",
  "framer motion": "#0055FF",
  framer: "#0055FF",
  redux: "#764ABC",
  prisma: "#2D3748",
  "node.js": "#339933",
  nodejs: "#339933",
  go: "#00ADD8",
  golang: "#00ADD8",
  gin: "#008CF0",
  "gin gonic": "#008CF0",
  swagger: "#85EA2D",
  php: "#777BB4",
  laravel: "#FF2D20",
  kotlin: "#7F52FF",
  "jetpack compose": "#4285F4",
  jetpackcompose: "#4285F4",
  postgresql: "#4169E1",
  postgres: "#4169E1",
  "postgre sql": "#4169E1",
  mysql: "#4479A1",
  "my sql": "#4479A1",
  firebase: "#DD2C00",
  supabase: "#3FCF8E",
  docker: "#2496ED",
  npm: "#CB3837",
  yarn: "#2C8EBB",
  sqlite: "#003B57",
}

export function StackIcon({
  name,
  className,
}: {
  name: string
  className?: string
}) {
  const key = name.trim().toLowerCase()
  const Icon = stackIcons[key] ?? Box
  const color = stackColors[key]
  return (
    <Icon
      className={className}
      style={color ? { color } : undefined}
      aria-hidden="true"
    />
  )
}